modLoader="javafml"
loaderVersion="[47,)" # Forge 1.20.1 is 47.x
license="All Rights Reserved"

[[mods]]
modId="waypoint"
version="1.0.0"
displayName="Waypoint Mod"
authors="Blue_Gamerwolf"
description='''
A Minecraft mod that adds waypoints, health sensors, curios, and more.
'''

[[dependencies.waypoint]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.waypoint]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.waypoint]]
modId="create"
mandatory=true
versionRange="[6.0.6,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.waypoint]]
modId="curios"
mandatory=true
versionRange="[5.10.0,)"
ordering="AFTER"
side="BOTH"
